import { defineConfig } from 'lyr';

export default defineConfig({
  title: '@yl-d/shared',
  favicon: 'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/assets/favicon.ico',
  link: [
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/arco.min.css',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/monaco-file-icon.css',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/luna-object-viewer.min.css',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/luna-console.min.css',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/@yl-d/components.min.css',
  ],
  devScript: [
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react.development.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react-dom.development.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/router.development.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react-router.development.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react-router-dom.development.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/jsx-runtime.polyfill.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/arco.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/arco-icon.min.js',
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/babel-standalone.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react-markdown.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/bignumber.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/html2canvas.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/jszip.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/pizzip.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/file-saver.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/docxtemplater.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/luna-object-viewer.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/luna-console.min.js",
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/@yl-d/components.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/@yl-d/code-editor.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/@yl-d/shared.min.js',
  ],
  buildScript: [
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react.production.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react-dom.production.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/router.production.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react-router.production.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react-router-dom.production.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/jsx-runtime.polyfill.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/arco.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/arco-icon.min.js',
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/babel-standalone.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/react-markdown.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/bignumber.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/html2canvas.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/jszip.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/pizzip.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/file-saver.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/docxtemplater.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/luna-object-viewer.min.js",
    "https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/luna-console.min.js",
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/@yl-d/components.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/@yl-d/code-editor.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/@yl-d/shared.min.js',
    'https://lyr-cli-oss.oss-cn-beijing.aliyuncs.com/cdn/track.min.js',
  ],
  serverPath: '/apis',
  docsRequire: {
    ArcoDesign: '@arco-design/web-react',
    lyrComponent: '@yl-d/components',
  },
  menus: [
    {
      label: '介绍',
      path: '/',
    },
    {
      label: '组件',
      path: '/components',
      children: [
        {
          label: 'asyncLoad',
          path: '/components/async-load',
        },
        {
          label: 'BigNumber',
          path: '/components/big-number',
        },
        {
          label: 'babelParse',
          path: '/components/babel-parse',
        },
        {
          label: 'ConsoleRender',
          path: '/components/console-render',
        },
        {
          label: 'copyToClipBoard',
          path: '/components/copy-to-clip-board',
        },
        {
          label: 'docxReplace',
          path: '/components/docx-replace',
        },
        {
          label: 'downloadFile',
          path: '/components/download-file',
        },
        {
          label: 'getElementSnapshot',
          path: '/components/get-element-snapshot',
        },
        {
          label: 'getUrlSearchParams',
          path: '/components/get-url-search-params',
        },
        {
          label: 'MarkdownViewer',
          path: '/components/markdown-viewer',
        },
        {
          label: 'ReactPlayground',
          path: '/components/react-playground',
        },
      ],
    },
  ],
});
